// <auto-generated />
using System;
using FraudCell.Transaction.Service.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FraudCell.Transaction.Service.Persistence.Migrations
{
    [DbContext(typeof(TransactionServiceDbContext))]
    partial class TransactionServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("txn")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FraudCell.BuildingBlocks.Messaging.Inbox.InboxMessage", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_id");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("consumer_name");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payload_hash");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("EventId", "ConsumerName")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_inbox_processed_at");

                    b.ToTable("inbox_messages", "txn");
                });

            modelBuilder.Entity("FraudCell.BuildingBlocks.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CausationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb")
                        .HasColumnName("headers");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LockOwner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lock_owner");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("producer");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("routing_key");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("subject_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("NextAttemptAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("outbox_messages", "txn");
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.AiAssessment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("AnalystCandidatesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("analyst_candidates");

                    b.Property<DateTimeOffset>("AssessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assessed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<string>("ExternalAssessmentId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("external_assessment_id");

                    b.Property<string>("FraudType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("fraud_type");

                    b.Property<bool>("IsLate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_late");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_version");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payload_hash");

                    b.Property<string>("ReasonCodesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reason_codes");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_level");

                    b.Property<decimal>("RiskScore")
                        .HasColumnType("numeric(6,5)")
                        .HasColumnName("risk_score");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("source_event_id");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_assessments");

                    b.HasIndex("ExternalAssessmentId")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_assessments_external");

                    b.HasIndex("SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_assessments_source_event");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_assessments_primary")
                        .HasFilter("is_primary = true");

                    b.HasIndex("TransactionId", "ReceivedAt")
                        .HasDatabaseName("ix_ai_assessments_transaction_time");

                    b.ToTable("ai_assessments", "txn");
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.AnalystEligibilityProjection", b =>
                {
                    b.Property<string>("AnalystId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("analyst_id");

                    b.Property<bool>("AssignmentEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("assignment_enabled");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastSourceEventId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("last_source_event_id");

                    b.Property<DateTimeOffset>("ProjectionUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("projection_updated_at");

                    b.Property<string>("RegionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("regions");

                    b.Property<DateTimeOffset>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at");

                    b.Property<string>("SpecialtiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("specialties");

                    b.HasKey("AnalystId")
                        .HasName("pk_analyst_eligibility_projection");

                    b.ToTable("analyst_eligibility_projection", "txn");
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.AnalystNote", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("author_role");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note_text");

                    b.Property<string>("ParentNoteId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("parent_note_id");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.HasKey("Id")
                        .HasName("pk_analyst_notes");

                    b.HasIndex("CaseId", "CreatedAt")
                        .HasDatabaseName("ix_analyst_notes_case_time");

                    b.ToTable("analyst_notes", "txn");
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.AnalystWorkload", b =>
                {
                    b.Property<string>("AnalystId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("analyst_id");

                    b.Property<int>("ActiveCaseCount")
                        .HasColumnType("integer")
                        .HasColumnName("active_case_count");

                    b.Property<DateTimeOffset?>("LastAssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_assigned_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("AnalystId")
                        .HasName("pk_analyst_workloads");

                    b.ToTable("analyst_workloads", "txn", t =>
                        {
                            t.HasCheckConstraint("ck_analyst_workloads_range", "active_case_count >= 0 AND active_case_count <= 10");
                        });
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.CaseAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("AnalystId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("analyst_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("assigned_by");

                    b.Property<string>("AssignmentReason")
                        .HasColumnType("text")
                        .HasColumnName("assignment_reason");

                    b.Property<string>("AssignmentSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("assignment_source");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_case_assignments");

                    b.HasIndex("CaseId")
                        .IsUnique()
                        .HasDatabaseName("ux_case_assignments_active_case")
                        .HasFilter("status IN ('ASSIGNED', 'IN_PROGRESS')");

                    b.HasIndex("AnalystId", "AssignedAt")
                        .HasDatabaseName("ix_case_assignments_analyst_active")
                        .HasFilter("status IN ('ASSIGNED', 'IN_PROGRESS')");

                    b.ToTable("case_assignments", "txn");
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.CaseOverride", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_role");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("case_id");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("new_value");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OverrideType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("override_type");

                    b.Property<string>("PreviousValue")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("previous_value");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("SourceEventId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("source_event_id");

                    b.HasKey("Id")
                        .HasName("pk_case_overrides");

                    b.HasIndex("CaseId", "OccurredAt")
                        .HasDatabaseName("ix_case_overrides_case_time");

                    b.ToTable("case_overrides", "txn");
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.CaseTransition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_role");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("case_id");

                    b.Property<long>("CaseVersionAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("case_version_after");

                    b.Property<long>("CaseVersionBefore")
                        .HasColumnType("bigint")
                        .HasColumnName("case_version_before");

                    b.Property<string>("CausationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("new_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("SourceEventId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("source_event_id");

                    b.Property<string>("TransitionSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("transition_source");

                    b.HasKey("Id")
                        .HasName("pk_case_transitions");

                    b.HasIndex("ActorId", "OccurredAt")
                        .HasDatabaseName("ix_case_transitions_actor_time")
                        .HasFilter("actor_id IS NOT NULL");

                    b.HasIndex("CaseId", "OccurredAt")
                        .HasDatabaseName("ix_case_transitions_case_time");

                    b.ToTable("case_transitions", "txn");
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.CustomerFeedback", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("case_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("customer_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("SourceEventId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("source_event_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_customer_feedback");

                    b.HasIndex("CaseId")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_feedback_case");

                    b.ToTable("customer_feedback", "txn", t =>
                        {
                            t.HasCheckConstraint("ck_customer_feedback_rating", "rating >= 1 AND rating <= 5");
                        });
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.CustomerVerification", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("requested_by");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Response")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("response");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_customer_verifications");

                    b.HasIndex("CaseId")
                        .IsUnique()
                        .HasDatabaseName("ux_verifications_pending_case")
                        .HasFilter("status = 'PENDING'");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_verifications_expiry")
                        .HasFilter("status = 'PENDING'");

                    b.ToTable("customer_verifications", "txn", t =>
                        {
                            t.HasCheckConstraint("ck_verifications_expiry", "expires_at > requested_at");
                        });
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.FraudTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("AssessmentDeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assessment_deadline_at");

                    b.Property<string>("AssessmentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("assessment_status");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("ControlStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("control_status");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("customer_id");

                    b.Property<string>("DeviceFingerprintHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_fingerprint_hash");

                    b.Property<string>("EffectiveFraudType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("effective_fraud_type");

                    b.Property<string>("EffectiveRiskLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("effective_risk_level");

                    b.Property<decimal?>("EffectiveRiskScore")
                        .HasColumnType("numeric(6,5)")
                        .HasColumnName("effective_risk_score");

                    b.Property<string>("ManualReviewReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("manual_review_reason");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("RecipientReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("recipient_reference");

                    b.Property<string>("ScreeningDecision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("screening_decision");

                    b.Property<string>("TransactionNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("transaction_no");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("transaction_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("AssessmentDeadlineAt")
                        .HasDatabaseName("ix_transactions_assessment_pending")
                        .HasFilter("assessment_status = 'PENDING'");

                    b.HasIndex("TransactionNo")
                        .IsUnique()
                        .HasDatabaseName("ux_transactions_no");

                    b.HasIndex("ControlStatus", "CreatedAt")
                        .HasDatabaseName("ix_transactions_control_status");

                    b.HasIndex("CustomerId", "OccurredAt")
                        .HasDatabaseName("ix_transactions_customer_time");

                    b.ToTable("transactions", "txn", t =>
                        {
                            t.HasCheckConstraint("ck_transactions_amount", "amount > 0");
                        });
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.IdempotencyRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("Scope", "ActorId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_scope_actor_key");

                    b.ToTable("idempotency_records", "txn");
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.RiskCase", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("AssignedAnalystId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("assigned_analyst_id");

                    b.Property<string>("AssignmentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("assignment_status");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset?>("ClosureDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closure_due_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("decided_by");

                    b.Property<string>("DecisionNote")
                        .HasColumnType("text")
                        .HasColumnName("decision_note");

                    b.Property<string>("EffectiveFraudType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("effective_fraud_type");

                    b.Property<string>("EffectiveRiskLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("effective_risk_level");

                    b.Property<decimal?>("EffectiveRiskScore")
                        .HasColumnType("numeric(6,5)")
                        .HasColumnName("effective_risk_score");

                    b.Property<string>("FinalDecision")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("final_decision");

                    b.Property<string>("PrimaryAssessmentId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("primary_assessment_id");

                    b.Property<DateTimeOffset?>("ReviewStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("review_started_at");

                    b.Property<DateTimeOffset?>("SlaBreachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_breached_at");

                    b.Property<DateTimeOffset>("SlaDeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_deadline_at");

                    b.Property<string>("SlaPriority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sla_priority");

                    b.Property<DateTimeOffset>("SlaStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_started_at");

                    b.Property<DateTimeOffset?>("SlaStoppedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_stopped_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("transaction_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_risk_cases");

                    b.HasIndex("ClosureDueAt")
                        .HasDatabaseName("ix_cases_closure_due")
                        .HasFilter("status IN ('ONAYLANDI', 'BLOKLANDI') AND closed_at IS NULL");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_cases_manual_queue")
                        .HasFilter("assignment_status = 'MANUAL_QUEUE'");

                    b.HasIndex("SlaDeadlineAt")
                        .HasDatabaseName("ix_cases_sla_due")
                        .HasFilter("sla_breached_at IS NULL AND final_decision IS NULL");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_risk_cases_transaction");

                    b.HasIndex("SlaPriority", "SlaDeadlineAt")
                        .HasDatabaseName("ix_cases_assignment_queue")
                        .HasFilter("assignment_status = 'QUEUED'");

                    b.HasIndex("AssignedAnalystId", "SlaPriority", "SlaDeadlineAt")
                        .HasDatabaseName("ix_cases_assigned_analyst")
                        .HasFilter("status IN ('ATANDI', 'INCELENIYOR', 'MUSTERI_DOGRULAMA')");

                    b.HasIndex("EffectiveRiskLevel", "Status", "CreatedAt")
                        .HasDatabaseName("ix_cases_risk_status_time");

                    b.ToTable("risk_cases", "txn", t =>
                        {
                            t.HasCheckConstraint("ck_risk_cases_block_note", "final_decision <> 'BLOCK' OR (decision_note IS NOT NULL AND char_length(trim(decision_note)) > 0)");

                            t.HasCheckConstraint("ck_risk_cases_closed", "status <> 'KAPANDI' OR closed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_risk_cases_final_decision", "(status IN ('ONAYLANDI','BLOKLANDI','KAPANDI') AND final_decision IS NOT NULL AND decided_at IS NOT NULL) OR (status NOT IN ('ONAYLANDI','BLOKLANDI','KAPANDI'))");
                        });
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.TemporaryBlock", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<string>("AppliedBy")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("applied_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("reason");

                    b.Property<string>("ReleaseReason")
                        .HasColumnType("text")
                        .HasColumnName("release_reason");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<string>("SourceEventId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("source_event_id");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_temporary_blocks");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_temp_blocks_active_transaction")
                        .HasFilter("released_at IS NULL");

                    b.HasIndex("TransactionId", "Reason")
                        .IsUnique()
                        .HasDatabaseName("ux_temp_blocks_active_reason")
                        .HasFilter("released_at IS NULL");

                    b.ToTable("temporary_blocks", "txn");
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.TransactionNumberCounter", b =>
                {
                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Year"));

                    b.Property<long>("LastValue")
                        .HasColumnType("bigint")
                        .HasColumnName("last_value");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Year")
                        .HasName("pk_transaction_number_counters");

                    b.ToTable("transaction_number_counters", "txn", t =>
                        {
                            t.HasCheckConstraint("ck_txn_counter_value", "last_value >= 0");

                            t.HasCheckConstraint("ck_txn_counter_year", "year >= 2020");
                        });
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.AiAssessment", b =>
                {
                    b.HasOne("FraudCell.Transaction.Service.Domain.FraudTransaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ai_assessments_transactions_transaction_id");
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.AnalystNote", b =>
                {
                    b.HasOne("FraudCell.Transaction.Service.Domain.RiskCase", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_analyst_notes_risk_cases_case_id");
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.CaseAssignment", b =>
                {
                    b.HasOne("FraudCell.Transaction.Service.Domain.RiskCase", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_case_assignments_risk_cases_case_id");
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.CaseOverride", b =>
                {
                    b.HasOne("FraudCell.Transaction.Service.Domain.RiskCase", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_case_overrides_risk_cases_case_id");
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.CaseTransition", b =>
                {
                    b.HasOne("FraudCell.Transaction.Service.Domain.RiskCase", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_case_transitions_risk_cases_case_id");
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.CustomerFeedback", b =>
                {
                    b.HasOne("FraudCell.Transaction.Service.Domain.RiskCase", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_feedback_risk_cases_case_id");
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.CustomerVerification", b =>
                {
                    b.HasOne("FraudCell.Transaction.Service.Domain.RiskCase", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_verifications_risk_cases_case_id");
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.RiskCase", b =>
                {
                    b.HasOne("FraudCell.Transaction.Service.Domain.FraudTransaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_risk_cases_transactions_transaction_id");
                });

            modelBuilder.Entity("FraudCell.Transaction.Service.Domain.TemporaryBlock", b =>
                {
                    b.HasOne("FraudCell.Transaction.Service.Domain.FraudTransaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_temporary_blocks_transactions_transaction_id");
                });
#pragma warning restore 612, 618
        }
    }
}
