// <auto-generated />
using System;
using FraudCell.Gamification.Service.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FraudCell.Gamification.Service.Persistence.Migrations
{
    [DbContext(typeof(GamificationServiceDbContext))]
    [Migration("20260722175809_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("game")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FraudCell.BuildingBlocks.Messaging.Inbox.InboxMessage", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_id");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("consumer_name");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payload_hash");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("EventId", "ConsumerName")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_inbox_processed_at");

                    b.ToTable("inbox_messages", "game");
                });

            modelBuilder.Entity("FraudCell.BuildingBlocks.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CausationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb")
                        .HasColumnName("headers");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LockOwner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lock_owner");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("producer");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("routing_key");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("subject_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("NextAttemptAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("outbox_messages", "game");
                });

            modelBuilder.Entity("FraudCell.Gamification.Service.Domain.AnalystDailyStat", b =>
                {
                    b.Property<string>("AnalystId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("analyst_id");

                    b.Property<DateOnly>("StatDate")
                        .HasColumnType("date")
                        .HasColumnName("stat_date");

                    b.Property<double?>("AverageDecisionSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("average_decision_seconds");

                    b.Property<int>("ConfirmedFraudCount")
                        .HasColumnType("integer")
                        .HasColumnName("confirmed_fraud_count");

                    b.Property<int>("DecisionCount")
                        .HasColumnType("integer")
                        .HasColumnName("decision_count");

                    b.Property<int>("FalsePositiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("false_positive_count");

                    b.Property<int>("FastDecisionCount")
                        .HasColumnType("integer")
                        .HasColumnName("fast_decision_count");

                    b.Property<long>("Points")
                        .HasColumnType("bigint")
                        .HasColumnName("points");

                    b.Property<int>("SlaBreachCount")
                        .HasColumnType("integer")
                        .HasColumnName("sla_breach_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("AnalystId", "StatDate")
                        .HasName("pk_analyst_daily_stats");

                    b.HasIndex("StatDate", "Points", "AnalystId")
                        .HasDatabaseName("ix_daily_stats_date_points");

                    b.ToTable("analyst_daily_stats", "game");
                });

            modelBuilder.Entity("FraudCell.Gamification.Service.Domain.AnalystFraudTypeStat", b =>
                {
                    b.Property<string>("AnalystId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("analyst_id");

                    b.Property<string>("FraudType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("fraud_type");

                    b.Property<decimal>("AccuracyRate")
                        .HasColumnType("numeric(6,5)")
                        .HasColumnName("accuracy_rate");

                    b.Property<int>("ConfirmedFraudCount")
                        .HasColumnType("integer")
                        .HasColumnName("confirmed_fraud_count");

                    b.Property<int>("CorrectDecisionCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_decision_count");

                    b.Property<int>("DecisionCount")
                        .HasColumnType("integer")
                        .HasColumnName("decision_count");

                    b.Property<int>("FalsePositiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("false_positive_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("AnalystId", "FraudType")
                        .HasName("pk_analyst_fraud_type_stats");

                    b.ToTable("analyst_fraud_type_stats", "game");
                });

            modelBuilder.Entity("FraudCell.Gamification.Service.Domain.AnalystPerformanceSummary", b =>
                {
                    b.Property<string>("AnalystId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("analyst_id");

                    b.Property<decimal>("AccuracyRate")
                        .HasColumnType("numeric(6,5)")
                        .HasColumnName("accuracy_rate");

                    b.Property<double?>("AverageDecisionSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("average_decision_seconds");

                    b.Property<int>("CorrectDecisions")
                        .HasColumnType("integer")
                        .HasColumnName("correct_decisions");

                    b.Property<int>("FalsePositiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("false_positive_count");

                    b.Property<int>("SlaBreachCount")
                        .HasColumnType("integer")
                        .HasColumnName("sla_breach_count");

                    b.Property<int>("SlaCompliantCount")
                        .HasColumnType("integer")
                        .HasColumnName("sla_compliant_count");

                    b.Property<long>("TotalDecisionSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("total_decision_seconds");

                    b.Property<int>("TotalDecisions")
                        .HasColumnType("integer")
                        .HasColumnName("total_decisions");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("AnalystId")
                        .HasName("pk_analyst_performance_summaries");

                    b.ToTable("analyst_performance_summaries", "game", t =>
                        {
                            t.HasCheckConstraint("ck_perf_summary_range", "total_decisions >= 0 AND correct_decisions >= 0 AND accuracy_rate >= 0 AND accuracy_rate <= 1");
                        });
                });

            modelBuilder.Entity("FraudCell.Gamification.Service.Domain.AnalystProfileProjection", b =>
                {
                    b.Property<string>("AnalystId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("analyst_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastSourceEventId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("last_source_event_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AnalystId")
                        .HasName("pk_analyst_profiles_projection");

                    b.ToTable("analyst_profiles_projection", "game");
                });

            modelBuilder.Entity("FraudCell.Gamification.Service.Domain.AnalystScoreSummary", b =>
                {
                    b.Property<string>("AnalystId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("analyst_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<int>("TotalBadges")
                        .HasColumnType("integer")
                        .HasColumnName("total_badges");

                    b.Property<int>("TotalDecisions")
                        .HasColumnType("integer")
                        .HasColumnName("total_decisions");

                    b.Property<long>("TotalPoints")
                        .HasColumnType("bigint")
                        .HasColumnName("total_points");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("AnalystId")
                        .HasName("pk_analyst_score_summaries");

                    b.ToTable("analyst_score_summaries", "game", t =>
                        {
                            t.HasCheckConstraint("ck_score_summary_nonneg", "total_decisions >= 0 AND total_badges >= 0");
                        });
                });

            modelBuilder.Entity("FraudCell.Gamification.Service.Domain.AnalystWeeklyStat", b =>
                {
                    b.Property<string>("AnalystId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("analyst_id");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date")
                        .HasColumnName("week_start_date");

                    b.Property<double?>("AverageDecisionSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("average_decision_seconds");

                    b.Property<int>("ConfirmedFraudCount")
                        .HasColumnType("integer")
                        .HasColumnName("confirmed_fraud_count");

                    b.Property<int>("DecisionCount")
                        .HasColumnType("integer")
                        .HasColumnName("decision_count");

                    b.Property<int>("FalsePositiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("false_positive_count");

                    b.Property<int>("FastDecisionCount")
                        .HasColumnType("integer")
                        .HasColumnName("fast_decision_count");

                    b.Property<long>("Points")
                        .HasColumnType("bigint")
                        .HasColumnName("points");

                    b.Property<int>("SlaBreachCount")
                        .HasColumnType("integer")
                        .HasColumnName("sla_breach_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("AnalystId", "WeekStartDate")
                        .HasName("pk_analyst_weekly_stats");

                    b.HasIndex("WeekStartDate", "Points", "AnalystId")
                        .HasDatabaseName("ix_weekly_stats_week_points");

                    b.ToTable("analyst_weekly_stats", "game");
                });

            modelBuilder.Entity("FraudCell.Gamification.Service.Domain.BadgeDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CriteriaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("criteria_version");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_badge_definitions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_badge_definitions_code");

                    b.ToTable("badge_definitions", "game");
                });

            modelBuilder.Entity("FraudCell.Gamification.Service.Domain.EarnedBadge", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("AnalystId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("analyst_id");

                    b.Property<string>("BadgeId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("badge_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CriteriaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("criteria_version");

                    b.Property<DateTimeOffset>("EarnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earned_at");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("source_event_id");

                    b.HasKey("Id")
                        .HasName("pk_earned_badges");

                    b.HasIndex("BadgeId")
                        .HasDatabaseName("ix_earned_badges_badge_id");

                    b.HasIndex("AnalystId", "BadgeId")
                        .IsUnique()
                        .HasDatabaseName("ux_earned_badges_analyst_badge");

                    b.HasIndex("AnalystId", "EarnedAt")
                        .HasDatabaseName("ix_earned_badges_analyst_time");

                    b.ToTable("earned_badges", "game");
                });

            modelBuilder.Entity("FraudCell.Gamification.Service.Domain.PointLedgerEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("AnalystId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("analyst_id");

                    b.Property<string>("CaseId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rule_code");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("source_event_id");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_point_ledger");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_point_ledger_case")
                        .HasFilter("case_id IS NOT NULL");

                    b.HasIndex("AnalystId", "OccurredAt")
                        .HasDatabaseName("ix_point_ledger_analyst_time");

                    b.HasIndex("OccurredAt", "AnalystId")
                        .HasDatabaseName("ix_point_ledger_daily");

                    b.HasIndex("SourceEventId", "RuleCode")
                        .IsUnique()
                        .HasDatabaseName("ux_point_ledger_event_rule");

                    b.ToTable("point_ledger", "game", t =>
                        {
                            t.HasCheckConstraint("ck_point_ledger_nonzero", "points <> 0");
                        });
                });

            modelBuilder.Entity("FraudCell.Gamification.Service.Domain.RuleEvaluation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("AnalystId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("analyst_id");

                    b.Property<string>("CaseId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rule_code");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("source_event_id");

                    b.HasKey("Id")
                        .HasName("pk_rule_evaluations");

                    b.HasIndex("SourceEventId", "RuleCode")
                        .IsUnique()
                        .HasDatabaseName("ux_rule_evaluations_event_rule");

                    b.ToTable("rule_evaluations", "game");
                });

            modelBuilder.Entity("FraudCell.Gamification.Service.Domain.EarnedBadge", b =>
                {
                    b.HasOne("FraudCell.Gamification.Service.Domain.BadgeDefinition", null)
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_earned_badges_badge_definitions_badge_id");
                });
#pragma warning restore 612, 618
        }
    }
}
